sunshine_admin:
    resource: "@SunshineAdminBundle/Controller/"
    type:     annotation
    prefix:   /

sunshine_organization:
    resource: "@SunshineOrganizationBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout